#!/usr/bin/env bash

set -e

GO="godep go"

echo "Building confd..."
OLD=`pwd`
cd confd
# Static compilation is useful when confd is run in a container
CGO_ENABLED=0 $GO build -a -installsuffix cgo -ldflags '-s' -o $OLD/bin/confd
